- hosts: full_box
  become: yes
  vars:
    ssl_cert_ca_delegate: "{{ inventory_hostname }}"
    ssl_cert_ca_delegate_name: kubernetes-ca
    ssl_cert_file_base_dir: /var/lib/kubernetes
  tasks:
    - include_role:
        name: jumperfly.ssl_cert
      vars:
        ssl_cert_type: intermediate
        ssl_cert_ca_delegate_name: ca
        ssl_cert_name: kubernetes-ca
        ssl_cert_file_base_dir: /etc/pki/ansible-ssl-certs
    - include_role:
        name: jumperfly.ssl_cert
      vars:
        ssl_cert_type: client
        ssl_cert_name: apiserver-etcd
        ssl_cert_ca_delegate_name: etcd-ca
    - include_role:
        name: jumperfly.ssl_cert
      vars:
        ssl_cert_type: server
        ssl_cert_name: apiserver
        ssl_cert_subject_common_name: kubernetes
        ssl_cert_hosts:
          - kubernetes
          - kubernetes.default
          - kubernetes.default.svc
          - kubernetes.default.svc.cluster
          - kubernetes.default.svc.cluster.local
          - "10.0.0.1"
          - "127.0.0.1"
    - include_role:
        name: jumperfly.ssl_cert
      vars:
        ssl_cert_type: peer
        ssl_cert_name: service-account
        ssl_cert_subject_common_name: service-account
    - include_role:
        name: jumperfly.ssl_cert
      vars:
        ssl_cert_type: client
        ssl_cert_name: controller-manager
        ssl_cert_subject_common_name: system:kube-controller-manager
    - include_role:
        name: jumperfly.ssl_cert
      vars:
        ssl_cert_type: client
        ssl_cert_name: scheduler
        ssl_cert_subject_common_name: system:kube-scheduler
- hosts: kube_master_nodes
  become: yes
  vars:
    kube_master_encrpytion_config_enabled: yes
    kube_master_enable_services: no
  pre_tasks:
    - name: Set etcd facts
      set_fact:
        etcd_client_listen_ip: "0.0.0.0"
        etcd_peer_listen_ip: "0.0.0.0"
  roles:
    - jumperfly.kubernetes_master
  post_tasks:
    - name: Clean yum cache
      command: yum clean all
      args:
        warn: no
- hosts: full_box
  become: yes
  gather_facts: no
  tasks:
    - name: Enable services
      service:
        name: "{{ item }}"
        enabled: yes
      loop:
        - kube-apiserver
        - kube-controller-manager
        - kube-scheduler
    - name: Stop etcd
      service:
        name: etcd
        state: stopped
    - name: Clear etcd lib dir
      file:
        path: /var/lib/etcd/default.etcd
        state: absent

